/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moyenne;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enock SKY
 */
public class Essaie_2 extends javax.swing.JFrame {
      DefaultTableModel d = new DefaultTableModel();
    int selectedrow;

    /**
     * Creates new form Essaie_2
     */
    
    
    double Calmoy;
    public Essaie_2() {
        initComponents();
        
        d=(DefaultTableModel)tableau.getModel();
        Calmoy=0;
        MOYDEV.setText("la moyenne total est de 0");
    }
    
    public void RemplirTable(JTable T){
       
        try {
            String requet = "select * from moy ORDER BY id ASC;";
               // DefaultTableModel model = new DefaultTableModel(null,moy);

           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tugas", "root", "");
            Statement state = con.createStatement();
            ResultSet result=state.executeQuery(requet);
             DefaultTableModel table= (DefaultTableModel) T.getModel();
         
     for(int i=table.getRowCount()-1;i>=0;i--){
                table.removeRow(i);
            }
           while(result.next()){
                Object line[]={result.getString("nom"),result.getString("prenom"),result.getInt("age")};
                table.addRow(line);
            }
    
    
              con.close();
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }                
    }
    
    private void Connection_table_colis() throws ClassNotFoundException{
    /*
        try{
        Class.forName("org.sqlite.JDBC");
         con =(Connection) DriverManger.getConnection("jbc:sqlite:gesbus.db");
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur"+e.getMessage());}*/
        
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MOYDEV = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        i1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        i2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        d3 = new javax.swing.JSpinner();
        Nom = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Age:");

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matière", "Inter1", "Inter2", "Dev1", "Dev2", "Coeff", "Moy Inter", "Moy Dev", "Moy coeff"
            }
        ));
        jScrollPane1.setViewportView(tableau);
        if (tableau.getColumnModel().getColumnCount() > 0) {
            tableau.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableau.getColumnModel().getColumn(1).setPreferredWidth(40);
            tableau.getColumnModel().getColumn(2).setPreferredWidth(40);
            tableau.getColumnModel().getColumn(3).setPreferredWidth(40);
            tableau.getColumnModel().getColumn(4).setPreferredWidth(40);
            tableau.getColumnModel().getColumn(5).setPreferredWidth(40);
            tableau.getColumnModel().getColumn(6).setPreferredWidth(50);
            tableau.getColumnModel().getColumn(7).setPreferredWidth(50);
            tableau.getColumnModel().getColumn(8).setPreferredWidth(50);
        }
        RemplirTable(tableau);

        jLabel4.setText("Matière");

        jLabel5.setText("Moyenne d'Interrogation:");

        MOYDEV.setText("Moyenne de Devoir:");

        jLabel7.setText("1er");

        jLabel8.setText("2em");

        jLabel9.setText("NOTE D'INTRROGATION");

        jLabel10.setText("NOTE DE DEVOIR");

        jLabel11.setText("1er");

        jLabel12.setText("2em");

        jButton1.setText("VALIDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Coeff");

        d3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomActionPerformed(evt);
            }
        });

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        jButton2.setText("supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(28, 28, 28)
                                .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MOYDEV))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(44, 44, 44)
                            .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {i1, i2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MOYDEV)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try{
            
          //String Mat,I1,I2,D1,D2;

       String Mat=mat.getText();
      double  I1= Double.parseDouble(i1.getText());
    double   I2= Double.parseDouble(i2.getText());
    double  D1= Double.parseDouble(d1.getText());
     double D2= Double.parseDouble(d2.getText()); 
     double MI= (I1+I2)/2;
         int D3=(Integer)d3.getValue();
                   double MD= (MI+D1+D2)/3;

          double MC= ((MI+D1+D2)/3)*D3;
         Object[]ligne = new Object []{Mat,I1,I2,D1,D2,D3,MI,MD,MC};
          d.addRow(ligne);
        Calmoy=+MC;
        MOYDEV.setText("La moyenne coefficié donne:"+Calmoy);
        
           String requet = "insert into moy(nom,prenom,age,I1,I2,moy_I,D1,D2,moy_D,coeff,moy_C) values(?,?,?,?,?,?,?,?,?,?,?)";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tugas", "root", "");
            
              PreparedStatement prepareState = con.prepareStatement(requet);
            prepareState.setString(1,  Nom.getText());
             prepareState.setString(2, Prenom.getText());
              prepareState.setInt(3, Integer.parseInt(Age.getText()));
              
            prepareState.setDouble(4, I1);
             prepareState.setDouble(5,I2);
              prepareState.setDouble(6, MI);
            prepareState.setDouble(7,  D1);
             prepareState.setDouble(8, D2);
              prepareState.setDouble(9,MD);
              
             prepareState.setInt(10, D3);
              prepareState.setDouble(11, MC);
              prepareState.executeUpdate();
            
            
         RemplirTable(tableau);
        
        
        /////////////////
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erreur de saisie");
             
        }
        
          
        Nom.setText("");
        Prenom.setText("");
        Age.setText("");
        mat.setText("");
      i1.setText("");
    i2.setText("");
   d1.setText("");
    d2.setText(""); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  // TODO add your handling code here:
        int row = tableau.getSelectedRow();
        
        if (row<0){
            JOptionPane.showMessageDialog(this,
                    "NO Row is selected! Please selact one row",
                    "Select row",
                    JOptionPane.ERROR_MESSAGE);
                    
                    }   else{
                    DefaultTableModel model = (DefaultTableModel) tableau.getModel();
                 //   Delate from moy Where id = row;
                    model.removeRow(row);
                    
        }
            //   pst=(PreparedStatement) con.prepareStatement("delate from moy where id =?");
             //  pst.setString(1,mat.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablModel = (DefaultTableModel) tableau.getModel();
        if(tableau.getSelectedRowCount()==1){
            String name = Nom.getText();
            String pren = Prenom.getText();
         int age= Integer.parseInt(Age.getText());
       String Mat=mat.getText();
      double  I1= Double.parseDouble(i1.getText());
    double   I2= Double.parseDouble(i2.getText());
    double  D1= Double.parseDouble(d1.getText());
     double D2= Double.parseDouble(d2.getText()); 
        
      tablModel.setValueAt(mat,tableau.getSelectedRow(),0);
       tablModel.setValueAt(i1,tableau.getSelectedRow(),1);
      tablModel.setValueAt(i2,tableau.getSelectedRow(),2);
      tablModel.setValueAt(d1,tableau.getSelectedRow(),3);
      tablModel.setValueAt(d2,tableau.getSelectedRow(),4);
    /*  tablModel.setValueAt(mat,tableau.getSelectedRow(),5);
      tablModel.setValueAt(mat,tableau.getSelectedRow(),6);
      tablModel.setValueAt(mat,tableau.getSelectedRow(),7);
      tablModel.setValueAt(mat,tableau.getSelectedRow(),8);
      tablModel.setValueAt(mat,tableau.getSelectedRow(),9);
      tablModel.setValueAt(mat,tableau.getSelectedRow(),10);*/
     

      
      JOptionPane.showMessageDialog(this, "Update successfully");


        
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Essaie_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Essaie_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Essaie_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Essaie_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Essaie_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel MOYDEV;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JSpinner d3;
    private javax.swing.JTextField i1;
    private javax.swing.JTextField i2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mat;
    private javax.swing.JTable tableau;
    // End of variables declaration//GEN-END:variables
}
